### PR TITLE
WIP new build and release code

### LINKED ISSUE #163: Please file/pin Releases....
Hi Greg,

I am using your component for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository), hope you don't mind.

Therefore I need source files in Pypi's SDIST format, or Github archives.
The source files on Pypi contain some code with outrageous paths, and no setup.py,
and: you do not file releases on Github.

At least, your release list on Github should look like this:
Bildschirmfoto 2020-09-01 um 21 01 34

To fix this, I created a fork of your code, and added the missing tags.
Until you fix this, I will point the SRC_URI of the Gentoo Ebuilds to the [fork](https://github.com/onkelbeh/pywemo) to have consistant snaps of the releases.

I did this with:
```bash
  699  git tag 0.4.46 d9cd5c2
  701  git tag 0.4.45 8727d71
  702  git tag 0.4.44 24ddfc8
  706  git tag 0.4.42 e165292
  707  git tag 0.4.43 2c13cc0
  708  git tag 0.4.34 10280d0
```
Your commit id's may differ.
Then I pushed the tags to github:

```bash
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git tag
0.4.34
0.4.42
0.4.43
0.4.44
0.4.45
0.4.46
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.34
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.34 -> 0.4.34
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.42
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.42 -> 0.4.42
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.43
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.43 -> 0.4.43
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.44
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.44 -> 0.4.44
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.45
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.45 -> 0.4.45
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.46
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.46 -> 0.4.46

```
So I get consistant archives:
```bash
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo # ls -la /usr/portage/distfiles/pywemo-0.4.*
-rw-rw-r-- 1 portage portage 38251  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.34.tar.gz
-rw-rw-r-- 1 portage portage 42439  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.43.tar.gz
-rw-rw-r-- 1 portage portage 43927  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.45.tar.gz
-rw-rw-r-- 1 portage portage 43923  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.46.tar.gz
```

The fix for issue [60](https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/60): https://github.com/onkelbeh/HomeAssistantRepository/commit/abe802941ea38bd3ff793a69f45e214cd30ed7db
Please do this for at least the versions pinned in Home Assistant.

Thank you very much.

### PR DESCRIPTION
**Pull request by pavoni**
## Description:
This is just a WIP version of some new build code moved from `pyvera`.

Given the comments here https://github.com/pavoni/pywemo/issues/163 I thought I should take a look at improving the build and release process.

However this is well outside my expertise. so the easist solution for me was to try and reuse what @vangorra did in reworking the `pyvera` release process.

@sqldiablo I know you're busy - but you had added some lint and other CI code here - so wanted to get your view on the best approach before I push ahead,

I have no issue dumping this (it was mostly just copied) if you prefer a different approach.

Other comments / help very welcome. I know I don't properly understand the build and release process!

### CODE REVIEW

**Comment by sqldiablo** [comment]
I've given this a quick review, but I need to look at it a little deeper later tonight.

**Review by sqldiablo — APPROVED** [review]

**Comment by sqldiablo** [comment]
Ok, I think I've made a sufficiently big mess of this PR...

To get this to merge, you'll need to go into settings for the repo and turn off the required checks for Travis CI for this branch, and master. https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks

**Comment by pavoni** [comment]
@sqldiablo Thanks so much for all your work on this. Looks like it all worked and published correctly to pypi - but if you have time please check you're happy with what happened.

Thanks again - I'm so grateful!

**Comment by sqldiablo** [comment]
I'll give this version a test w/ Home Assistant today or tomorrow. If everything checks out, I'll PR a change into Home Assistant to have it use this new version.

**Comment by sqldiablo** [comment]
Looking at the logs of the build and publish actions, they seem to check out.

**Comment by pavoni** [comment]
Thanks. I'll put together another PR to remove ghost files etc.

**Comment by sqldiablo** [comment]
I was finally able to get my Home Assistant dev environment rebuilt and tested this successfully. I've opened a PR to bump the pyWeMo version in Home Assistant Core to 0.5.0.

**Pull request merged**
