### PR TITLE
Add coveralls, take 2

### PR DESCRIPTION
**Pull request by Spectre5**
## Description:
See #223, I've added coveralls to the build script instead.  It would get run on pull requests as well now, but I don't think that causes an issue.

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.

### CODE REVIEW

**Comment by pavoni** [comment]
I'll merge this and then we can check it works.

If it does I think it would be pretty easy to change it to only run when we publish - which is perhaps better.

**Comment by pavoni** [comment]
Fantastic - thanks.

Let me know what you think about just running it on publish.

**Comment by Spectre5** [comment]
Right.  So right now it runs on a PR, on push, and on release (publish).  In the README, you can select to show whichever badge you want from shields.io, so I think it is fine to run coveralls on all of those, and then you can display in the README whichever one you want.  I think showing the coverage from the current state of the master branch makes the most sense though.

**Comment by pavoni** [comment]
That's perfect. And agree the `master` branch makes most sense.

**Pull request merged**
