### PR TITLE
Tidy ghost files etc

### PR DESCRIPTION
**Pull request by pavoni**
## Description:
Remove files from old build process that are no longer needed.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.

### CODE REVIEW

**Review by sqldiablo — APPROVED** [review]
I'm fine with this, but we'll need to looking into getting pytest running happily with the new build process now. It's commented-out currently. I have black commented-out because it's misbehaving as well.

**Comment by pavoni** [comment]
I uncommented pytest  - and it worked fine for me both locally and here. Can you try again?

I also stopped everything running twice on a PR. We can check it still runs on a merge to master when we merge.

Black is another story...

**Comment by sqldiablo** [comment]
Your successful build is evidence that it's working now, as that's the issue I was having on the other PR. I'm fine with this PR getting merged in at this point.

**Comment by pavoni** [comment]
Thanks for your help.

**Pull request merged**
