### PR TITLE
Coffee maker

### PR DESCRIPTION
**Pull request by stu-gott**
Add support for Wemo Coffee Makers

### CODE REVIEW

**Comment by pavoni** [comment]
@stu-gott thanks for the contribution.

Your host change looks good - will double check on my set-up - but your suggestion makes sense.

There looks to be some subscription code commented out - and a `subscription_callback` function that isn't used at this point.

I suspect you had in mind to do what I never got to - which is to use the callback data to update the device state.

Very happy for you to do this (although it would need careful testing) - also happy to merge a simplified version that works like the rest of the library.

The library is mostly used by home_assistant at this point - and HA just calls for a state update when it receives the callback. It's not perfect - but better that the polling it did before!

Let me know what you'd like to do. Do you plan to use this directly - or in HA?

Thanks again - Greg

**Comment by stu-gott** [comment]
this is for HA. I will commit my patch for that to my fork when I get a
chance. I saw where you were using update() and that's what
subscription_callback is for here. the commented code was an example of how
to use that function. but since I closed the loop and have a patch for HA
too that's pretty much irrelevant at this point.

**Comment by stu-gott** [comment]
https://github.com/stu-gott/home-assistant/tree/wemo-coffeemaker

This is the tree with the matching HA changes in place.

**Comment by pavoni** [comment]
Thanks - now released as `0.4.10`.

Thanks for the contribution.

**Pull request merged**
