### PR TITLE
Allow connecting to wemo devices directly

### PR DESCRIPTION
**Pull request by kk7ds**
This patch addresses two issues for me:
1. I'd like to be able to talk to wemos directly over a VPN by IP
2. The discovery mechanism is very unreliable at times

This patch allows this behavior by letting a user specify a device
manually by the URL needed to reach it. In order to make this work,
we need to implement the rediscovery procedure differently because
we can't expect to be able to find it via SSDP.

If mac is set to None, then we probe for the port the wemo is currently
using, based on the list of seen-in-the-wild ports we know they can
be on.

I've been using a variant of this in a local fork of pywemo for a
while and have found it to be much more reliable than depending on
discovery for initial setup and rediscovery.

### CODE REVIEW

**Comment by kk7ds** [comment]
Hi,

I'd like to add static wemo support to HA and need something like this available. I've been using a local fork of this approach with a lot of success for a couple of months.

What do you think?

**Comment by kk7ds** [comment]
By the way, you can test this locally with something like this:

```
import logging
import pywemo

logging.basicConfig(level=logging.DEBUG)
s = pywemo.Switch('http://192.168.50.183:49153/setup.xml', None)
s.reconnect_with_device()
```

**Comment by pavoni** [comment]
Certainly agree discovery is shaky. How do you initially find the devices (and at least get the ip addresses)? How safe is the Port range? Guess I should check / trace mine...

**Comment by kk7ds** [comment]
My local wemos are quarantined onto a separate subnet that I isolate from the internet (and the other subnets). Thus, I control that one pretty tightly, which includes the addresses of the devices. Since they never change address, there's really no need to have the discovery process going. Plus, being across subnets, the discovery won't work (or requires some roundabout hacks to make it work).

The other use is for some wemos we have in a vacation home that I can access over a VPN. I don't want to do discovery over that tunnel of course, so I'd like to be able to point at them directly. They don't ever change address, but if they did, I can collect the addresses from my router's DHCP lease log.

**Comment by kk7ds** [comment]
This is what I was going to propose for HA:

http://pastebin.com/wVzPhByx

**Comment by kk7ds** [comment]
Oh, and on the port range thing... After running for a few months, I've seen them cycle mostly between 49152 and 49153. I saw 49154 one time after a semi-weird restart during a firmware restart process. This is across wall switches, the original plug switch, insights, and one wemo bridge. None of them ever jumped outside that range, so I think it's fairly safe.

Since the probing goes really quick, we could expand it to 49150-49160 or something if you want. I've just never seen it be necessary.

**Comment by pavoni** [comment]
I think this is a good idea. Rediscovery is shaky even on a network where it does work. It also seems that changing ports is much more common than changing ip.

So I think what would make sense is to combine the two approaches, so if we lose contact we try your probe first - and fall back to discovery if we need to. 

Would you be OK to change to do this? I'll double check my port numbers - but what you say makes sense.

**Comment by kk7ds** [comment]
Sure, no problem. I thought about doing this first, since usually a port-rescan goes really fast (unless the device is gone, and then it's just the timeout). I just didn't want to overly alter the discovery mechanism for those that use it.

I'll cook up a change later in the morning.

Thanks!

**Comment by kk7ds** [comment]
@pavoni Did you see that I updated the commit? Thoughts?

Thanks!

**Comment by pavoni** [comment]
I didn't - will take a look - thanks.

**Comment by pavoni** [comment]
Looks good - thanks.

**Comment by pavoni** [comment]
Released as 0.3.10. Thanks.

**Pull request merged**
