### PR TITLE
Fix rediscovery issue

### PR DESCRIPTION
**Pull request by sqldiablo**

### CODE REVIEW

**Comment by sqldiablo** [comment]
@pavoni, can you please merge this when you get a chance?

**Comment by pavoni** [comment]
Have merged both your PRs, and bumped the version to `0.4.32` but get a gateway error when I try to upload to pypi - will try again later.

**Comment by pavoni** [comment]
Now released.

**Comment by sqldiablo** [comment]
Excellent! Thanks, @pavoni.

**Pull request merged**
