### PR TITLE
add coverage

### PR DESCRIPTION
**Pull request by Spectre5**
## Description:

With the addition of new tests and plans for more, I'd like to include coverage.  @pavoni, you might consider signing up for coveralls too (and could add a badge to the README), but it isn't that important either.

Needed to bump pytest to over 6.0 so it can read from pyproject.toml (putting outputs into .cache/pytest now), and obviously added coverage dependency and a few options for it to pyproject.toml too.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.

### CODE REVIEW

**Review by esev — APPROVED** [review]
Nice idea

**Comment by Spectre5** [comment]
Added changing one of the regex in `conftest.py` to a raw string to quiet/fix this pytest warning:

```
tests/conftest.py:22
  /home/scott/Coding/github/pywemo/tests/conftest.py:22: DeprecationWarning: invalid escape sequence \d
    b'uuid:([A-Z][a-z]+-\d_\d)-[A-Za-z0-9]+',
```

**Comment by pavoni** [comment]
I've signed up for coverage.io - and added the token to the github secrets `CODECOV_TOKEN`.

I started to look at how to submit - and then ran out of time. But if you already know how to do this - please go ahead!

**Comment by Spectre5** [comment]
You mean coveralls.io?  If so, you can just name the secret `COVERALLS_REPO_TOKEN` and then we just add coveralls as another dev dependency, then call `coveralls` after `coverage`.  I'll take a closer look later as I also don't have time right this minute!

**Comment by pavoni** [comment]
Now added as `COVERALLS_REPO_TOKEN` (just while it was fresh in my mind - no rush!).

**Pull request merged**
