### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by sqldiablo**
Add Travis CI functionality to the Github repo.

### CODE REVIEW

**Comment by sqldiablo** [comment]
@pavoni If you're ok with it, I'd like to setup Travis CI on this repo. This PR is to setup the requirements for that. For now, all tests are optional, so the builds should always pass. Once you approve, I'll merge this in, and then you'll need to go to https://travis-ci.org and enable builds for this repo. I'm working on cleaning up the pylint, pydocstyle, and flake8 issues as we speak, but there are a ton of issues, so it'll take a bit.

**Review by pavoni — APPROVED** [review]
Great idea!

**Comment by sqldiablo** [comment]
Thanks, @pavoni. Can you enable Travis for this repo? You'll need to visit https://travis-ci.org/account/repositories and turn on the repo.

**Comment by pavoni** [comment]
Done - let me know if you need any of the default settings changed.

**Comment by sqldiablo** [comment]
Awesome, thanks. I think the defaults should be good. I'll let you know if we need to tweak anything.

**Pull request merged**
