### PR TITLE
Cleanup of Humidifier device (pylint errors)

### PR DESCRIPTION
**Pull request by sqldiablo**
Various cleanups and refactorings of the Humidifier device to fix pylint and other coding convention issues.

### CODE REVIEW

**Comment by sqldiablo** [comment]
The following errors are still hanging around, but being a n00b at Python, I'm not quite sure how to fix them:

C: 11, 4: Missing class docstring (missing-docstring)
R: 11, 4: Too few public methods (0/2) (too-few-public-methods)
F: 14, 4: Unable to import 'enum' (import-error)
C: 20, 0: Missing class docstring (missing-docstring)
R: 20, 0: Too few public methods (0/2) (too-few-public-methods)
C: 56, 0: Missing class docstring (missing-docstring)
R: 56, 0: Too few public methods (0/2) (too-few-public-methods)
R: 67, 0: Too many branches (15/12) (too-many-branches)
E:148,15: Instance of 'Humidifier' has no 'deviceevent' member (no-member)
E:267, 8: Instance of 'Humidifier' has no 'deviceevent' member (no-member)
E:280, 8: Instance of 'Humidifier' has no 'deviceevent' member (no-member)
E:294, 8: Instance of 'Humidifier' has no 'deviceevent' member (no-member)
R:122, 0: Too many public methods (29/20) (too-many-public-methods)

**Comment by sqldiablo** [comment]
By the way, I'm able to unit test the humidifier device just fine, so these are strictly syntactical issues and nothing preventing it from functioning as expected.

**Comment by pavoni** [comment]
Now released as 0.4.23. Thanks for your contribution!

**Comment by sqldiablo** [comment]
Excellent, and thanks for helping me through the process.

**Pull request merged**
