### PR TITLE
Handle device = None during scan

### PR DESCRIPTION
**Pull request by pavoni**
Fixes https://github.com/balloob/pywemo/issues/14

### CODE REVIEW

**Comment by balloob** [comment]
Looks good. Will you push a new release?

**Comment by pavoni** [comment]
Love to - my first time - so can you point me in the right direction?

**Comment by balloob** [comment]
On a clean copy of the latest master type

```
python3 setup.py sdist bdist_wheel upload 
```

**Comment by pavoni** [comment]
Thanks - done. 

Will do a PR to update the HA version.

**Pull request merged**
