### PR TITLE
Linting fixes

### LINKED ISSUE #119: Fix Linting Issues
Fix the plethora of code smell/formatting issues (pylint, flake8, and pydocstyle).

### PR DESCRIPTION
**Pull request by sqldiablo**
Numerous fixes for linting & syntax problems.

Fixes #119

## Checklist:
  - [x] The code change is tested and works locally.

### CODE REVIEW

**Comment by sqldiablo** [comment]
@pavoni Can you please review this massive PR and test it locally? My testing has passed, but I don't have some of the devices (like the CoffeeMaker or the Maker).

**Comment by sqldiablo** [comment]
@pavoni, I've been testing this pretty thoroughly with my Home Assistant install and myriad of WeMo devices. If you don't object, I'm going to merge this is. I have another PR on deck behind it, and then I want to cut a new version of pywemo so I can do a PR to Home Assistant that needs those changes.

**Comment by pavoni** [comment]
I have an hour free later - so can test it against a Maker (I don't have a coffee machine) - and can take a quick look if that would be helpful.

Although given it's mostly formatting changes I'm fine if you've tested, are happy and want to merge. 

Since this has mostly been a single maintainter repo - that has been the process to date!

**Comment by sqldiablo** [comment]
I'm going to go ahead and merge this one because I have one with some more significant changes to it that I'll open right after this, and you can test that one for me. :-)

**Pull request merged**
