### PR TITLE
Add integration tests for the F7C027, F7C063 and WSP080 switches

### PR DESCRIPTION
**Pull request by esev**
## Description:

Add integration tests for the F7C027, F7C063 and WSP080 switches.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.

### CODE REVIEW

**Comment by pavoni** [comment]
I have a couple of UK Insight Switches, a regular SNS switch and a Maker. They look to be the same model number (except with UK at the end) - so assume that just the different electrical hardware.

So I think we're covered except for the Maker - I'll add a similar test once we've merged this.

**Comment by pavoni** [comment]
I added the Maker tests https://github.com/pavoni/pywemo/pull/208

**Comment by pavoni** [comment]
Looks good to me!

**Comment by Spectre5** [comment]
same!

**Comment by Spectre5** [comment]
@esev - I know I previously advocated for removing the body from the cassettes, but now I'm wondering to myself if that was the wrong move and if it would make more sense to instead actually explicitly check the body as part of the test.  I mentioned that "we know what we sent the device", but if we check that what pywemo sends compared to the cassette then it adds some assurance that we still send the same thing in the future too (in case that part of the code changes or refactors at some point).  The main issue I see would be if we intentionally changed the signature (i.e. spacing or something), then we'd just need to make sure we updated all of the cassettes to match the new signature as part of the same PR.

**Comment by esev** [comment]
@Spectre5 - sounds good. See #217

**Pull request merged**
