### PR TITLE
Add black and isort

### PR DESCRIPTION
**Pull request by Spectre5**
## Description:  Add black and isort, bump pylint

Let me first say that this looks like a much bigger change that it is.  In terms of the code itself, there should effectively be no change at all.  I saw from build.sh that black is "temporarily" disabled, so I took a shot and enabling it, along with isort.  I also updated pylint to 2.6.0 since they removed the bad-continuation with that version.  You could break down this commit into the following:

- Add black section to pyproject.toml as well as black and isort dependencies (for dev version) and bumping pylint.
- Edits configs files so that pylint, flake8, and black are all enabled for all files except those in the `xsd` directory.  This does make flake8 and pylint take a little longer since they check more files, but it isn't too bad.  All of them expect the PEP8 recommended 79 characters per line.
- Edit the build.sh to enable support for isort and black
- Edit pylintrc to enable some "good names" and make some edits to code comments for those (removed some pylint locally disabled checks)
- Some minor code comment updates to support flake8 and pylint (since they are enabled for more files than previously --- they are now enabled on the `ouimeaux_device` directory, just not the lower `xsd` directory).
- The poetry.lock file has been updated and re-locked for these new libraries (and there are many other changes in terms of re-ordering the other dependencies as I found and mention in issue #181)

Most of the file changes in this PR were updated entirely by black and isort by running `black .` and `isort .` after they were added with poetry.  My local build is clean and all checks and tests pass.  I've also deleted the poetry.lock file and virtual environment to try testing it "from scratch" and it worked for me too.

**Related issue (if applicable):** N/A

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.

### CODE REVIEW

**Comment by Spectre5** [comment]
Also feel free to just close this PR if you're not interested in adding these

**Comment by pavoni** [comment]
Thanks for taking the time to do this. 

I had a go a while back and had black, pylint and isort fighting each other - but sounds like you resolved this!

**Comment by Spectre5** [comment]
I think so, at least locally and in the github CI.  Have you had a chance to test it and play around with it?  Are you interested in merge this?

**Comment by pavoni** [comment]
All good - works nicely.

Thanks for taking the time to do this.

I've added you as a contributor - hope that's OK.

**Pull request merged**
