### PR TITLE
Initial commit for WeMo Humidifier device

### PR DESCRIPTION
**Pull request by sqldiablo**
Added a device for the WeMo Humidifier and bumped the version number of pywemo.

### CODE REVIEW

**Comment by sqldiablo** [comment]
@pavoni or anyone else who has some time, can you please review this pull request? I'd like to get this functionality added because it's a prerequisite to me extending the wemo functionality in HA to support the WeMo Humidifier as well.

Thanks for taking the time to look look this over for me.

**Comment by pavoni** [comment]
Looks like you're using using 8 space indentation (the rest of the code uses 4). I guess it's possible you're using tabs and github is showing spaces. Be grateful if you could switch to 4 spaces.

Otherwise looks great - and happy to merge. Thanks for the contribution!

**Comment by sqldiablo** [comment]
That was my mistake. I was using tab indentation instead of spaces. I just pushed a commit to change humidifier.py over to 4-space indentation. Please let me know if that's better.

**Comment by pavoni** [comment]
I've merged this - but there are a few pep8 / pylint errors that would be nice to fix, before we release.

Quite a few of them look like editor settings (leaving whitespace on blank lines, trailing whitespace).
A few lines that would be good to split.
And some camelcase variable names that should be snake case. (Sorry for missing them - I'm mostly writing js these days).

The pywemo code is far from clean - but I'm trying to slowly improve it.
Don't worry about the pylint docstring errors.

**Pull request merged**
