### PR TITLE
Switch from netifaces to ifaddr.

### PR DESCRIPTION
**Pull request by mrstegeman**
ifaddr is pure Python and does not require a toolchain to be
installed.

### CODE REVIEW

**Comment by mrstegeman** [comment]
No idea how to fix the pylint issue.

**Comment by sqldiablo** [comment]
It looks like this is an issue with the pylint version we're using. I'm working on updating our requirements_test.txt to fix this.

**Comment by sqldiablo** [comment]
I'll try to get this tested this weekend and will merge it in if all goes well. Thanks for your contribution.

**Comment by sqldiablo** [comment]
Tested successfully. Thanks for your contribution.

**Comment by sqldiablo** [comment]
Published as version 0.4.40

**Comment by mrstegeman** [comment]
Thank you!

**Comment by pavoni** [comment]
Thanks for the contribution @mrstegeman 
And thanks for reviewing, merging and releasing @sqldiablo

**Pull request merged**
