### PR TITLE
add module docstring

### PR DESCRIPTION
**Pull request by Spectre5**
## Description:
Test to see if CI works...

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.

### CODE REVIEW

**Comment by pavoni** [comment]
Is this any help?

https://github.com/AndreMiras/coveralls-python-action

**Comment by Spectre5** [comment]
I hadn't seen that, could certainly try it instead.  Funny how the error I get here is different than what @esev is getting in his current PR (and I re-triggered the checks to be sure it was current).  I don't see why they would be different for this issue.  I'll continue to look into it, both what I've done and/or trying that action you linked to, which I had not seen.

**Comment by Spectre5** [comment]
Lots of current information about this issue [here](https://github.com/TheKevJames/coveralls-python/issues/252).  Looks like this last change is working, but is currently frozen on "waiting for status to be reported"

Perhaps you need to "remove the outdated check in the protected branch settings of the repository settings", based on [this page](https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157).  I'm not exactly sure what that means though.

Another related question though, what are these two checks that are "Expected".  I don't see how or where they are defined, as the 3 completed ones with check marks are the tree we've defined in the build.yml file.  ~What creates these ones?~ These [status checks](https://docs.github.com/en/github/administering-a-repository/troubleshooting-required-status-checks) are an option in the github settings.
Screenshot from 2021-01-30 15-58-00

**Comment by pavoni** [comment]
I’ve reset the branch protection rules to the new names.

**Comment by Spectre5** [comment]
Just for my own future understanding, can you clarify exactly what that means?  Which new names - was it me adding the "name" to the jobs or something else?

**Comment by pavoni** [comment]
looks like there is a list of recent actions

9FC23C09-0410-40E2-A0EA-1B495AB3F5E3

**Comment by Spectre5** [comment]
ah ok, so yes it must be from me changing the name to "Build and test" in that job.  I think it was just "build", as a default with no specially defined name, before.  Thanks!

**Comment by Spectre5** [comment]
This "name" line is newly added by me.  So before it just defaulted to "build" from the job identifier.
```
  build:
    name: Build and test
```

**Comment by pavoni** [comment]
Thanks for your hard work implementing this.

**Pull request merged**
