### PR TITLE
Device type is a switch not a humidifier

### PR DESCRIPTION
**Pull request by bpaauwe**
Set the device type string to a more correct value for this type of device.

## Description:

**Related issue (if applicable):** fixes #<pywemo issue number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] There is no commented out code in this PR.

### CODE REVIEW

**Comment by sqldiablo** [comment]
I'm not sure I agree with this change. All of the devices have descriptive device types like CoffeeMaker, Humidifier, Motion, and so on. @pavoni, what do you think?

@bpaauwe, what is the reason you would like to make this change? Is this helping to fix an issue with something that is using this module?

**Comment by bpaauwe** [comment]
@sqldiablo did you actually look at the change?  It looks like commit 952d6edff48011db8ae21df2ae2b591fd14063f3 - Add device_type property to device classes was done by pasting the same code in to each device file and then changing the device type appropriately, but the switch device file didn't get updated after the paste.  

Yes, without fixing this it does cause issues because you can't identify switches by device_type, they show up as humidifiers.  I'm trying to update https://github.com/rl1131/udi-wemo-poly to support more device types, specifically the Wemo Mini switch.

**Comment by sqldiablo** [comment]
Bob, I apologize. I saw the Humidifier value and thought it was for the Humidifier device, and not the switch device. My mistake. This is approved, and I will merge it in for you. Thanks for catching this.

**Comment by sqldiablo** [comment]
Published as version 0.4.41

**Comment by bpaauwe** [comment]
Thanks @sqldiablo!

**Comment by pavoni** [comment]
Thanks to both of you for contributing and merging. Can't believe we missed it for so long!

**Pull request merged**
