### PR TITLE
Combine all requests timeouts into a single constant

### PR DESCRIPTION
**Pull request by esev**
## Checklist:
  - [X] The code change is tested and works locally.
  - [X] There is no commented out code in this PR.

### CODE REVIEW

**Comment by Spectre5** [comment]
Makes sense, should we also add a timeout to all requests?  For example in `rules_db` there is the line `response = requests.get(rule_db_url)`.  I think there are a few others too

**Comment by Spectre5** [comment]
service.py has 1 more too,  `xml = requests.get(url, timeout=10)`

**Comment by esev** [comment]
Nice catch! Thank you.

**Comment by esev** [comment]
> Makes sense, should we also add a timeout to all requests?

I think so. The default is to wait indefinitely, which may block things. Did you see any other places?

**Comment by Spectre5** [comment]
Just those two

**Pull request merged**
