### PR TITLE
Add support for Wemo CrockPot Slow Cooker

### PR DESCRIPTION
**Pull request by alexanv1**
## Description:
Add support for [Wemo CrockPot Slow Cooker](https://www.belkin.com/us/support-article?articleNum=101177#:~:text=%20%20%201%20Step%201%3A%20Open%20the,instructions...%206%20Step%2010%3A%20Tap%20NEXT.%20More%20)

Old device that's probably out of production at this point but still supported by Wemo. I've been running with this for awhile but finally got around to contributing the changes after cleaning them up.

**Related issue (if applicable):** fixes #<pywemo issue number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.
  - [x] I have read and agree to the [CONTRIBUTING document](
        https://github.com/pavoni/pywemo/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alexanv1** [comment]
@esev could you please take a look at this when you get a chance.
Thanks!

**Review by esev — CHANGES_REQUESTED** [review]
Just a few lint issues found. See the details in the failing checks.

I think just running isort & black should take care of them. There is a `scripts/build.sh` file that should take care of running these too.

**Comment by esev** [comment]
> @esev could you please take a look at this when you get a chance. Thanks!

Very nice. Thank you for this PR.

**Comment by alexanv1** [comment]
> Just a few lint issues found. See the details in the failing checks.
> 
> I think just running isort & black should take care of them. There is a `scripts/build.sh` file that should take care of running these too.

Thanks! Should be fixed now.

**Review by esev — APPROVED** [review]
I pushed a few more pylint/flake8 updates to this PR. build.sh completes successfully now.

The current check failure is unrelated to this PR. I've fixed the underlying issue in #294.

**Comment by esev** [comment]
Thank you again for this PR @alexanv1

I created a new release, version [0.6.8](https://github.com/pywemo/pywemo/releases/tag/0.6.8), that includes your change.

**Comment by esev** [comment]
One more thing, @alexanv1 . If you have time, please consider contributing an integration test for the CrockPot. This helps us validate changes when we don't have the device to test with. We use the vcr library to record/replay the actual request/responses from the device.

See #205, #207, #208, and #214 for examples.

**Comment by alexanv1** [comment]
@esev, thanks for merging and releasing the update!
Sure, I will see if I can add integration tests within the few days if I have some time to figure out the vcr library.

**Comment by esev** [comment]
@alexanv1 just FYI I bumped the pywemo version in Home Assistant. It includes this PR now.
https://github.com/home-assistant/core/pull/62360

**Pull request merged**
